name: Build NanoDump

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mingw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 gcc-mingw-w64 g++-mingw-w64
      - name: Build with MinGW
        run: make -f Makefile.mingw
      - name: List generated files
        run: |
          echo "Listing files in current directory and subdirectories:"
          find . -type f
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nanodump-mingw
          path: |
            dist
            scripts

  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build with MSVC
        run: nmake -f Makefile.msvc
        shell: cmd
      - name: List generated files
        run: |
          echo "Listing files in current directory and subdirectories:"
          dir /s
        shell: cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nanodump-msvc
          path: |
            dist\*.exe
            dist\*.dll
            scripts\*.exe
